<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
  * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_MageShop
 * @version     1.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 */
/**
 * Home page template
 */
?>
<div class="banner">
	<div class="banner-inner">
	<?php echo $this->_getChildHtml('home'); ?>
	</div>
</div>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home_category_images')->toHtml(); ?> 
<div class="new-products">
<div class="new-products-inner">
<div class="new"><?php echo $this->getLayout()->createBlock('catalog/product_new')->setTemplate('catalog/product/new.phtml')->toHtml(); ?></div>
<div class="sellers"><?php echo $this->getLayout()->createBlock('mageshop/popular')->setTemplate('catalog/product/popular.phtml')->toHtml(); ?></div>
</div>
</div>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home_sitepolicy_block')->toHtml(); ?> 